#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times.
#
# Requirements:
#
# You must use the while loop (for and until are forbidden
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	((i++))
done
