#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
#
# Requirements:
#
# You must use the while loop (for and until are forbidden)
# You must use the if statement
i=1
while [ $i -le 9 ]
do
	echo "Hello School"
	((i++))
	if [ "$i" == 9 ]; then
		echo "Hi"
	fi
done	
